version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "beta-data-manager"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1hbsexfjopjt4"
s3_prefix = "beta-data-manager"
region = "us-east-1"
profile = "personal"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "deployStage=\"beta\" DataReceiverQueue=\"data-receiver\" DataEventQueue=\"data-event\" UserId=\"4636267\""
image_repositories = []
