version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "beta-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1hbsexfjopjt4"
s3_prefix = "beta-api"
region = "us-east-1"
profile = "personal"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "deployStage=\"beta\" UserId=\"4636267\""
image_repositories = []
