AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: UAG IoT project - data manager service.
Parameters:
  deployStage:
    Type: String
    Default: beta
    AllowedValues:
      - beta
      - prod
    Description: Environment of this stack of resources.
  UserId:
    Type: String
    Description: User ID to identify queues and functions names.

Globals:
  Function:
    Runtime: python3.8
    Timeout: 60
    MemorySize: 256

Mappings:
  Global:
    Functions:
      dataReader: data-reader

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      EndpointConfiguration:
        Type: REGIONAL
  DataReader: 
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join [ "", [!FindInMap [Global,Functions, dataReader],  !Sub "-${UserId}"]]
      AutoPublishAlias: live
      CodeUri: src/
      Handler: app.lambda_handler
      Environment:
        Variables:
          TABLE_NAME: 
            !ImportValue 
              'Fn::Sub': "dataTableName-${UserId}"
      Description: Lambda to read data from DynamoDB.
      Policies:
        - Version: '2012-10-17'
          Statement:
              Sid: "DataReaderFunctionPermissions"
              Effect: Allow
              Action:
                - dynamoDb:*
              Resource:
                  - '*'
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /sensors
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
Outputs:
  dataReaderFunctionOutput:
    Description: "Lambda ARN"
    Value: !GetAtt DataReader.Arn
  ApiIdOutput:
    Description: "API ID"
    Value: !Ref ApiGatewayApi
